// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using websitebenhvien.Data;

#nullable disable

namespace websitebenhvien.Migrations
{
    [DbContext(typeof(MyDbcontext))]
    [Migration("20241217012216_up_table_Specialty_1")]
    partial class up_table_Specialty_1
    {
        protected void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // existing code
        }
    }
}
