// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using websitebenhvien.Data;

#nullable disable

namespace websitebenhvien.Migrations
{
    [DbContext(typeof(MyDbcontext))]
    [Migration("20241217004116_Specialty")]
    partial class Specialty
    {
        // Remove the override keyword as there is no suitable method to override
        protected void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // The rest of the method implementation remains unchanged
            // ...
#pragma warning restore 612, 618
        }
    }
}
